### ISSUE TITLE
Update the incident-import-tools to use ArcREST

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/incident-import-tools#1]
Update the incident-import-tools to use ArcREST

**Comment by allisonmuise** [comment]
This update is required for Portal support

**Comment by allisonmuise** [comment]
Develop branch has been updated with tools that use arcrest to directly update a service rather than republishing. This update also allows for processign all files in a directory, rather than a single incident file.

This has required nearly completely re-writing these tools (scripts, GP tool UI, and configuration file). Significant testing will be required, particularly in these areas:

- [ ] Server service, address data, delete duplicates
- [ ] Server service, address data, don't delete duplicates
- [ ] Server service, coordinate data, delete duplicates, delete zeros
- [ ] Server service, coordinate data, don't delete duplicates, delete zeros
- [ ] Server service, coordinate data, delete duplicates, don't delete zeros
- [ ] Server service, coordinate data, don't delete duplicates, don't delete zeros

- [ ] Portal service, address data, delete duplicates
- [ ] Portal service, address data, don't delete duplicates
- [ ] Portal service, coordinate data, delete duplicates, delete zeros
- [ ] Portal service, coordinate data, don't delete duplicates, delete zeros
- [ ] Portal service, coordinate data, delete duplicates, don't delete zeros
- [ ] Portal service, coordinate data, don't delete duplicates, don't delete zeros

- [ ] Public & private AGOL service, address data, delete duplicates
- [ ] Public & private AGOL service, address data, don't delete duplicates
- [ ] Public & private AGOL service, coordinate data, delete duplicates, delete zeros
- [ ] Public & private AGOL service, coordinate data, don't delete duplicates, delete zeros
- [ ] Public & private AGOL service, coordinate data, delete duplicates, don't delete zeros
- [ ] Public & private AGOL service, coordinate data, don't delete duplicates, don't delete zeros

- [ ] Summary field specified
- [ ] No summary field specified
- [ ] Address in one field
- [ ] Address in many fields

cc @WalterPotts @ScottOppmann @LindsayThomas

**Comment by allisonmuise** [comment]
Also note: This update will require 'installing' arcrest. The necessary folders - arcrest and arcresthelper - are included. These folders must be copied to the Python Lib directory; typically C:\Python27\ArcGIS10.3\Lib.
